export const futbolistas = [
    {
      name: 'Karim Benzema',
      description: 'Jugador de fútbol francés',
      photo: 'https://example.com/benzema.jpg',
      rating: 0,
      totalRatings: 0,
      averageRating: 0,
    },
    {
      name: 'Lionel Messi',
      description: 'Jugador de fútbol argentino, considerado uno de los mejores de la historia',
      photo: 'https://example.com/messi.jpg',
      rating: 0,
      totalRatings: 0,
      averageRating: 0,
    },
    {
      name: 'Cristiano Ronaldo',
      description: 'Jugador de fútbol portugués, conocido por su habilidad goleadora',
      photo: 'https://example.com/ronaldo.jpg',
      rating: 0,
      totalRatings: 0,
      averageRating: 0,
    },
    {
      name: 'Neymar Jr',
      description: 'Jugador de fútbol brasileño, conocido por su habilidad técnica y regates',
      photo: 'https://example.com/neymar.jpg',
      rating: 0,
      totalRatings: 0,
      averageRating: 0,
    },
    {
      name: 'Luis Suárez',
      description: 'Jugador de fútbol uruguayo, conocido por su instinto goleador',
      photo: 'https://example.com/suarez.jpg',
      rating: 0,
      totalRatings: 0,
      averageRating: 0,
    },
  ];
  
  export const frutas = [
    {
      name: 'Manzana',
      description: 'Fruta agridulce rica en fibra y vitamina C',
      photo: 'https://example.com/apple.jpg',
      rating: 0,
      totalRatings: 0,
      averageRating: 0,
    },
    {
      name: 'Banana',
      description: 'Fruta tropical rica en potasio',
      photo: 'https://example.com/banana.jpg',
      rating: 0,
      totalRatings: 0,
      averageRating: 0,
    },
    {
      name: 'Naranja',
      description: 'Fruta cítrica y jugosa, rica en vitamina C',
      photo: 'https://example.com/orange.jpg',
      rating: 0,
      totalRatings: 0,
      averageRating: 0,
    },
    {
      name: 'Pera',
      description: 'Fruta dulce y jugosa, rica en fibra y antioxidantes',
      photo: 'https://example.com/pear.jpg',
      rating: 0,
      totalRatings: 0,
      averageRating: 0,
    },
    {
      name: 'Uva',
      description: 'Fruta pequeña y redonda, rica en antioxidantes',
      photo: 'https://example.com/grape.jpg',
      rating: 0,
      totalRatings: 0,
      averageRating: 0,
    },
  ];
  
  export const peliculas = [
    {
      name: 'El Padrino',
      description: 'Clásico del cine dirigido por Francis Ford Coppola',
      photo: 'https://example.com/godfather.jpg',
      rating: 0,
      totalRatings: 0,
      averageRating: 0,
    },
    {
      name: 'Titanic',
      description: 'Película romántica y dramática dirigida por James Cameron',
      photo: 'https://example.com/titanic.jpg',
      rating: 0,
      totalRatings: 0,
      averageRating: 0,
    },
    {
      name: 'Avatar',
      description: 'Película de ciencia ficción también dirigida por James Cameron',
      photo: 'https://example.com/avatar.jpg',
      rating: 0,
      totalRatings: 0,
      averageRating: 0,
    },
    {
      name: 'El Rey León',
      description: 'Clásico de Disney que cuenta la historia de Simba',
      photo: 'https://example.com/lionking.jpg',
      rating: 0,
      totalRatings: 0,
      averageRating: 0,
    },
    {
      name: 'Harry Potter y la piedra filosofal',
      description: 'Primera película de la saga basada en los libros de J.K. Rowling',
      photo: 'https://example.com/harrypotter.jpg',
      rating: 0,
      totalRatings: 0,
      averageRating: 0,
    },
  ];
  
  export const bandas = [
    {
      name: 'Queen',
      description: 'Icono del rock con éxitos como "Bohemian Rhapsody"',
      photo: 'https://example.com/queen.jpg',
      rating: 0,
      totalRatings: 0,
      averageRating: 0,
    },
    {
      name: 'The Beatles',
      description: 'Banda de rock británica activa durante la década de 1960',
      photo: 'https://example.com/beatles.jpg',
      rating: 0,
      totalRatings: 0,
      averageRating: 0,
    },
    {
      name: 'Rolling Stones',
      description: 'Banda de rock británica formada en 1962',
      photo: 'https://example.com/rollingstones.jpg',
      rating: 0,
      totalRatings: 0,
      averageRating: 0,
    },
    {
      name: 'Led Zeppelin',
      description: 'Banda de rock formada en 1968, conocida por su influencia en el hard rock',
      photo: 'https://example.com/ledzeppelin.jpg',
      rating: 0,
      totalRatings: 0,
      averageRating: 0,
    },
    {
      name: 'Pink Floyd',
      description: 'Banda de rock psicodélico y progresivo',
      photo: 'https://example.com/pinkfloyd.jpg',
      rating: 0,
      totalRatings: 0,
      averageRating: 0,
    },
  ];
  